version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mqtt-broker:
    build:
      context: ./broker
      dockerfile: Dockerfile
    image: mqtt-broker:latest
    restart: always
    ports:
      - "${MQTT_PORT}:1883"
    depends_on:
      - postgres
    networks:
      - app-network

  nestjs:
    build: .
    restart: always
    ports:
      - "${APP_PORT}:3000"
      - "3001:3001"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MQTT_BROKER_URL: mqtt://mqtt-broker:${MQTT_PORT}
    depends_on:
      - postgres
      - mqtt-broker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
